/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetRowsResponse {
  /**
   * List of rows
   */
  rows: {
    /**
     * The id of the row
     */
    id: number;
    /**
     * The value of the row
     */
    value: string;
    /**
     * The timestamp of the row
     */
    timestamp: string;
  }[];
}
